[package]
name = "serializer"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
serde = { version = "1.0.217", features = ["serde_derive"] }
uuid = { version = "1.13.2", features = ["v7", "v8"] }
